### PR TITLE
Feature/episode pages

### PR DESCRIPTION
**Pull request by Vannsl**

### CODE REVIEW

**Comment by KnisterPeter** [comment]
@Vannsl is this ready for review?

**Comment by Vannsl** [comment]
@KnisterPeter sorry for the late answer. I decided after a couple of days that I want to have a few design changes and continued working here without setting the WIP prefix. I ping y'all as soon as I'm ready with my changes and I also did some specs.

**Comment by Vannsl** [comment]
@KnisterPeter @programmiri Finally ready for review.

This is how the /podcast page will look like for several episodes:

screencapture-localhost-3000-podcast-2020-07-05-13_21_38
screencapture-localhost-3000-podcast-2020-07-05-13_21_06

**Comment by Vannsl** [comment]
Hey everybody, if it's okay I would merge this now. You can still comment later and I will add the changes. Thank you :)

**Comment by programmiri** [comment]
Sorry @Vannsl 

I think it looks really good & I will have to go through the source code at some point to get a better grip on svelte :D

**Pull request merged**
